apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: madrid-rental-finder

resources:
- ../../base

# Image tags — updated by CI pipeline (approach B: commit tag bumps)
# CI runs: kustomize edit set image ...
images:
- name: dahomelab.azurecr.io/madrid-rental-finder/api
  newName: dahomelab.azurecr.io/madrid-rental-finder/api
  newTag: sha-bf331dfd2944073735c25ba9c1f247b62be1ab3f
- name: dahomelab.azurecr.io/madrid-rental-finder/dashboard
  newName: dahomelab.azurecr.io/madrid-rental-finder/dashboard
  newTag: sha-bf331dfd2944073735c25ba9c1f247b62be1ab3f

patches:
- path: resources-patch.yaml
