apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: madrid-rental-finder

resources:
  - ../../base

# Image tags — updated by CI pipeline (approach B: commit tag bumps)
# CI runs: kustomize edit set image ...
images:
  - name: dahomelab.azurecr.io/madrid-rental-finder/api
    newTag: v1.0.1
  - name: dahomelab.azurecr.io/madrid-rental-finder/dashboard
    newTag: v1.0.2

patches:
  - path: resources-patch.yaml
